### PR TITLE
Fix #19 and #20

### LINKED ISSUE #19: Before Cron skills not working
**What is the bug?**
Before Cron skills are not working, if the user has his day start at 00:00 / 12 am and `AUTO_CRON` is disabled

**Additional context**
After some debugging I found `nowAdjusted.getHours() == dayStart-1` not to be working, since `dayStart` will be `0` and `Date.getHours()` will never return `0 - 1 = -1`.

**How often does this happen?**
Every time given
* `AUTO_CRON` is disabled
* AND
* day start is at 00:00

**Script version**
Automate Habitica v0.29.32 (beta) by @bumbleshoot

**Script settings**
```javascript
const AUTO_CRON = false; // true or false

const AUTO_ACCEPT_QUEST_INVITES = true;

const FORCE_START_QUESTS = false; // party leaders only
const FORCE_START_QUESTS_AFTER_HOURS = 1; // eg. if set to 1, quests will force start after 1h
const NOTIFY_MEMBERS_EXCLUDED_FROM_QUEST = false;

const AUTO_INVITE_GOLD_QUESTS = false;
const AUTO_INVITE_UNLOCKABLE_QUESTS = false;
const AUTO_INVITE_PET_QUESTS = false;
const AUTO_INVITE_HOURGLASS_QUESTS = false;
const PM_WHEN_OUT_OF_QUEST_SCROLLS = false;

const NOTIFY_ON_QUEST_END = true;

const AUTO_CAST_SKILLS = true;

const AUTO_PAUSE_RESUME_DAMAGE = false;
const MAX_PLAYER_DAMAGE = 20;
const MAX_PARTY_DAMAGE = 5;

const AUTO_ALLOCATE_STAT_POINTS = true;
const STAT_TO_ALLOCATE = "str"; // str, int, con, per

const AUTO_PURCHASE_GEMS = true; // subscribers only

const AUTO_PURCHASE_ARMOIRES = true;
const RESERVE_GOLD = 10000;

const AUTO_SELL_EGGS = false;
const RESERVE_EGGS = 999;

const AUTO_SELL_HATCHING_POTIONS = false;
const RESERVE_HATCHING_POTIONS = 999;

const AUTO_SELL_FOOD = false;
const RESERVE_FOOD = 999;

const AUTO_HATCH_FEED_PETS = true;
const ONLY_USE_DROP_FOOD = true;

const HIDE_PARTY_NOTIFICATIONS = false;
const HIDE_ALL_GUILD_NOTIFICATIONS = false;
const HIDE_NOTIFICATIONS_FROM_SPECIFIC_GUILDS = [ // only used if HIDE_ALL_GUILD_NOTIFICATIONS is false
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", // enter a guild ID between the quotes to hide notifications from that guild
  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" // repeat for as many guilds as you want
]
```

### PR DESCRIPTION
**Pull request by ramotar**
As promised, I provide you with a fix to bugs #19 and #20.

I have seen, you already implemented a quick fix. Just have a look if my version suits you :)

**One important remark:**
The timestamp of `lastCron` needs to be timezone-adjusted as well!

### CODE REVIEW

**Comment by bumbleshoot** [comment]
Hi, thanks for your work on this! I will stick with my fixes to issues #19 ([here](https://github.com/bumbleshoot/automate-habitica/commit/5355c7eec43a210273d20db243a0cecddc456dc9)) and #20 ([here](https://github.com/bumbleshoot/automate-habitica/commit/c12a2f5a1561da1d6c71233985ec643474bcf611)), because they are much simpler.

`lastCron` does not need to be time zone adjusted, because `new Date()` sets both `lastCron` and `lastAfterCron` to the script's time zone. As long as they are both in the same time zone, the script can compare them to determine which one came first. :)

**Comment by ramotar** [comment]
Hi @bumbleshoot,
can you do me a small favor and shortly reopen this PR?
I have some funny business going on with the branch leading to this PR and I'm hoping this might resolve it.

**Comment by bumbleshoot** [comment]
@ramotar Done, please let me know when I can close this pull request again. :)

**Comment by ramotar** [comment]
@bumbleshoot Thank you very much, I was able to resolve everything :)

**Pull request closed without merging**
