### PR TITLE
Implement #23

### PR DESCRIPTION
**Pull request by ramotar**
Implements an automatic stat allocation "algorithm", that simply allocates to the primary stat of the users class.

### CODE REVIEW

**Comment by bumbleshoot** [comment]
Hi @ramotar, thanks for your work on this! There are lots of ways users might choose to allocate their stats - allocating all stat points to the primary stat is not always necessarily the best strategy. It depends on the user's class and their play style. Someday, I would like to give users more control over stat allocation (ie. rather than all stat points going to one stat, the user can distribute them automatically to all four stats however they want). This is on my list of "nice to have" features that I will build someday if I have time. :)

**Comment by ramotar** [comment]
Hi @bumbleshoot,
can you do me a small favor and shortly reopen this PR?
I have some funny business going on with the branch leading to this PR and I'm hoping this might resolve it.

**Comment by bumbleshoot** [comment]
Hi @ramotar, I cannot reopen this pull request because "The ramotar-auto-start-allocate branch was force-pushed or recreated."

**Comment by ramotar** [comment]
Hi @bumbleshoot,
can you please check, if you can open it now?

**Comment by bumbleshoot** [comment]
@ramotar Done, please let me know when I can close this pull request again. :)

**Comment by ramotar** [comment]
@bumbleshoot Thank you very much, I was able to resolve everything :)

**Pull request closed without merging**
